baseURL: 'https://cloudpanda1.github.io'
title: CLOUDPANDA
theme: hugo-theme-ladder
license: MIT
licenselink: 'https://github.com/guangzhengli/hugo-theme-ladder/blob/master/LICENSE'
description: 'A simple blog'
homepage: 'https://cloudpanda1.github.io/'
defaultContentLanguage: 'en'
paginate: 10
menu:
  main:
    - name: Blog
      url: /blog
      weight: 1
    - name: Tags
      url: /tags
      weight: 2
    - name: Archive
      url: /archives
      weight: 3
params:
  brand: CLOUDPANDA
  avatarURL: /images/avatar.png
  author: cloudpanda
  authorDescription: Just a person doing stuff
  info: Probably won't write much
  favicon: /images/avatar.png
  options:
    showDarkMode: true
    enableImgZooming: true
    enableMultiLang: false
  darkModeTheme: data-dark-mode
  #darkModeTheme: icy-dark-mode
languages:
  en:
    languageName: EN
taxonomies:
  series: series
  tag: tags
